name: Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install dependencies
              run: lerna bootstrap
            - name: Run API tests
              run: lerna run test --scope api

    test-web:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install dependencies
              run: lerna bootstrap
            - name: Run web tests
              run: lerna run test --scope web
